- name: Update system locales
  listen: localectl update locale
  ansible.builtin.command: "{{ locale_update }}"
  changed_when: true
  when: ansible_connection not in ["container", "docker", "community.docker.docker"]
